export const paises = [
    'QATAR',
    'ECUADOR',
    'SENEGAL',
    'HOLANDA',
    'INGLATERRA',
    'IRÁN',
    'ESTADOS UNIDOS',
    'GALES',
    'ARGENTINA',
    'ARABIA SAUDITA',
    'MÉXICO',
    'POLONIA',
    'FRANCIA',
    'AUSTRALIA',
    'DINAMARCA',
    'TÚNEZ',
    'ESPAÑA',
    'COSTA RICA',
    'ALEMANIA',
    'JAPÓN',
    'BÉLGICA',
    'CANADÁ',
    'MARRUECOS',
    'CROACIA',
    'BRASIL',
    'SERBIA',
    'SUIZA',
    'CAMERÚN',
    'PORTUGAL',
    'GHANA',
    'URUGUAY',
    'COREA DEL SUR'
]